edition = "2021"

format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Item"
newline_style = "Unix"
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true